import { mk, BLK, WHT } from './helpers';

const mueb  = mk('hogar', 'muebles');
const ilum  = mk('hogar', 'iluminacion');
const deco  = mk('hogar', 'decoracion');
const texti = mk('hogar', 'textiles');

export const hogar = [
  mueb('Sofá 3 Cuerpos Nórdico Tela Gris', 'Mueblesa', 799, 4,
    'Sofá de 3 cuerpos tapizado en tela de alta resistencia, patas de madera maciza y relleno de espuma HD.',
    ['#a0a0a0', '#c8b89a', '#3a3a3a']),
  mueb('Mesa de Comedor Roble 6 Personas', 'Falabella Home', 599, 3,
    'Mesa de comedor en madera de roble 160x90cm, patas metálicas en negro y superficie lacada mate.',
    ['#8a6a4a', BLK]),
  mueb('Cama Doble con Cajones 140x190', 'IKEA', 449, 5,
    'Cama doble con 4 cajones de almacenamiento, cabecero acolchado y somier incluido. Medida 140x190cm.',
    [WHT, '#8a6a4a', BLK]),
  mueb('Silla de Escritorio Ergonómica', 'HM Casa', 249, 8,
    'Silla ergonómica con soporte lumbar ajustable, apoyabrazos 3D, altura regulable y base giratoria.',
    [BLK, '#c8c0b0']),
  mueb('Escritorio Nórdico Minimalista 120cm', 'Sodimac', 299, 6,
    'Escritorio de 120x60cm en tablero MDP con estructura metálica, cajón lateral y superficie resistente.',
    ['#f0ead0', BLK]),
  mueb('Velador de Madera con Cajón', 'IKEA', 129, 12,
    'Velador de madera con un cajón, estante inferior y patas de madera maciza. Diseño escandinavo.',
    ['#f0ead0', '#8a6a4a']),

  ilum('Lámpara de Pie Arco Metal Negro 180cm', 'Philips', 189, 7,
    'Lámpara de pie arco con pantalla de tela, base circular de mármol y brazo metálico negro 180cm.', [BLK]),
  ilum('Lámpara Colgante Industrial Edison', 'Brilliant', 89, 14,
    'Lámpara colgante industrial con estructura metálica, socket E27 y cable textil trenzado 1.5m.',
    [BLK, '#c8a87a']),
  ilum('Velador LED Táctil 3 Intensidades', 'Brilliant', 49, 20,
    'Velador táctil LED con 3 niveles de intensidad, función timer, luz cálida 3000K y batería recargable.',
    [WHT, '#c8a87a']),
  ilum('Tira LED RGB 5m Control Remoto', 'Govee', 39, 30,
    'Tira LED RGB 5m con control remoto y app, 16 millones de colores, IP65 y corte cada 10cm.'),
  ilum('Aplique de Pared LED Nórdico', 'Philips', 69, 15,
    'Aplique de pared LED nórdico, 12W, luz cálida 3000K, cuerpo de aluminio y ángulo ajustable.',
    [WHT, BLK, '#c8a87a']),

  deco('Cuadro Canvas Abstracto 80x100cm', 'Art Studio', 89, 10,
    'Cuadro canvas con impresión de arte abstracto, marco de madera y listo para colgar. 80x100cm.'),
  deco('Espejo Redondo Dorado 80cm', 'HM Casa', 119, 7,
    'Espejo redondo con marco metálico dorado 80cm de diámetro. Ideal para entradas y living.', ['#c8a83a']),
  deco('Maceta Cerámica con Soporte Bambú', 'IKEA', 39, 25,
    'Set maceta de cerámica esmaltada con soporte de bambú, disponible en 3 tamaños.',
    [WHT, '#c87a5a', '#5a8a5a']),
  deco('Jarrón Decorativo Estilo Mármol', 'Zara Home', 59, 18,
    'Jarrón decorativo en cerámica con efecto mármol negro y dorado, 30cm de altura.', [WHT, BLK]),
  deco('Set de Velas Aromáticas x3 Premium', 'Yankee Candle', 29, 35,
    'Set 3 velas aromáticas de parafina en vasija de vidrio con aromas vainilla, lavanda y cedro.'),

  texti('Juego de Sábanas Percal 300 Hilos', 'Sheraton', 79, 15,
    'Juego de sábanas (bajera, encimera y 2 fundas) en algodón percal 300 hilos. Suave y fresco.',
    [WHT, '#c8d0d8', '#c8b89a'], ['1.5 plazas', '2 plazas', '2.5 plazas']),
  texti('Plumón de Plumas Doble 220x240cm', 'Sheraton', 149, 8,
    'Plumón de plumas de ganso 90/10, funda 100% algodón, temperatura media y funda protectora incluida.',
    [WHT], ['1.5 plazas', '2 plazas']),
  texti('Alfombra Boho Tejida a Mano 200x290', 'HM Casa', 199, 5,
    'Alfombra tejida a mano con lana y algodón reciclado, diseño boho multicolor, 200x290cm.',
    ['#c8b89a', '#8a6a4a']),
  texti('Set Cojines Decorativos x4 Terciopelo', 'Zara Home', 59, 20,
    'Set de 4 cojines de terciopelo 45x45cm con cierre oculto. Mix de texturas y colores neutros.',
    ['#c8b89a', '#5a6a7a', '#3a3a3a']),
  texti('Cortinas Blackout Lino 140x220cm', 'HM Casa', 99, 12,
    'Cortinas blackout de lino sintético, 140x220cm, anillas incluidas, bloqueo de luz 99% y colores neutros.',
    ['#f0f0e8', '#c8c0b0', BLK]),
];
